### ISSUE TITLE
Assignment 4

### ISSUE THREAD

**Issue by ghost** [VIS-2129-F2020/wanjikungare-vis#3]
Hi both, 
I think this is an assignment that didn't come through when I committed everything else previously. 

https://github.com/VIS-2129-F2020/wanjikungare-vis/blob/master/Vis_Assignment-4.html

Wanjiku

**Comment by c-voulgaris** [comment]
On line 16, add a space after the ## to format as a heading

Add an empty line before lines 61 and 71 to move these headings onto their own lines and format them as headings

This includes five of the required six maps.
